INSERT INTO arc.dm_d_val_xref (val_id,val_desc,itm_mn,subj_area,src_sys_cd,dai_crt_dttm,dai_updt_dttm,dai_etl_id) VALUES
  (1,'Core Tot Sales check from submission','SUBMITM','SALES','CORE',SYSDATE,SYSDATE,1),
  (2,'Core Sales check from submission','DARZALEX','SALES','CORE',SYSDATE,SYSDATE,1),
  (3,'Core Sales check from submission','DOXIL','SALES','CORE',SYSDATE,SYSDATE,1),
  (4,'Core Sales check from submission','ERLEADA','SALES','CORE',SYSDATE,SYSDATE,1),
  (5,'Core Sales check from submission','INVEGA','SALES','CORE',SYSDATE,SYSDATE,1),
  (6,'Core Sales check from submission','INVEGA SUSTENNA','SALES','CORE',SYSDATE,SYSDATE,1),
  (7,'Core Sales check from submission','INVEGA TRINZA','SALES','CORE',SYSDATE,SYSDATE,1),
  (8,'Core Sales check from submission','INVOKAMET','SALES','CORE',SYSDATE,SYSDATE,1),
  (9,'Core Sales check from submission','INVOKAMET XR','SALES','CORE',SYSDATE,SYSDATE,1),
  (10,'Core Sales check from submission','INVOKANA','SALES','CORE',SYSDATE,SYSDATE,1),
  (11,'Core Sales check from submission','PREZCOBIX','SALES','CORE',SYSDATE,SYSDATE,1),
  (12,'Core Sales check from submission','PREZISTA','SALES','CORE',SYSDATE,SYSDATE,1),
  (13,'Core Sales check from submission','PROCRIT','SALES','CORE',SYSDATE,SYSDATE,1),
  (14,'Core Sales check from submission','REMICADE','SALES','CORE',SYSDATE,SYSDATE,1),
  (15,'Core Sales check from submission','RISPERDAL CONSTA','SALES','CORE',SYSDATE,SYSDATE,1),
  (16,'Core Sales check from submission','SIMPONI','SALES','CORE',SYSDATE,SYSDATE,1),
  (17,'Core Sales check from submission','SIMPONI ARIA','SALES','CORE',SYSDATE,SYSDATE,1),
  (18,'Core Sales check from submission','SPRAVATO','SALES','CORE',SYSDATE,SYSDATE,1),
  (19,'Core Sales check from submission','STELARA','SALES','CORE',SYSDATE,SYSDATE,1),
  (20,'Core Sales check from submission','SYMTUZA','SALES','CORE',SYSDATE,SYSDATE,1),
  (21,'Core Sales check from submission','TREMFYA','SALES','CORE',SYSDATE,SYSDATE,1),
  (22,'Core Sales check from submission','XARELTO','SALES','CORE',SYSDATE,SYSDATE,1),
  (23,'Core Sales check from submission','YONDELIS','SALES','CORE',SYSDATE,SYSDATE,1),
  (24,'Core Sales check from submission','ZYTIGA','SALES','CORE',SYSDATE,SYSDATE,1),
  (25,'Core Tot Rebates validation check','ADJITEM','REBATES','CORE',SYSDATE,SYSDATE,1),
  (26,'Core Rebates validation check','DARZALEX','REBATES','CORE',SYSDATE,SYSDATE,1),
  (27,'Core Rebates validation check','DOXIL','REBATES','CORE',SYSDATE,SYSDATE,1),
  (28,'Core Rebates validation check','ERLEADA','REBATES','CORE',SYSDATE,SYSDATE,1),
  (29,'Core Rebates validation check','INVEGA','REBATES','CORE',SYSDATE,SYSDATE,1),
  (30,'Core Rebates validation check','INVEGA SUSTENNA','REBATES','CORE',SYSDATE,SYSDATE,1),
  (31,'Core Rebates validation check','INVEGA TRINZA','REBATES','CORE',SYSDATE,SYSDATE,1),
  (32,'Core Rebates validation check','INVOKAMET','REBATES','CORE',SYSDATE,SYSDATE,1),
  (33,'Core Rebates validation check','INVOKAMET XR','REBATES','CORE',SYSDATE,SYSDATE,1),
  (34,'Core Rebates validation check','INVOKANA','REBATES','CORE',SYSDATE,SYSDATE,1),
  (35,'Core Rebates validation check','PREZCOBIX','REBATES','CORE',SYSDATE,SYSDATE,1),
  (36,'Core Rebates validation check','PREZISTA','REBATES','CORE',SYSDATE,SYSDATE,1),
  (37,'Core Rebates validation check','PROCRIT','REBATES','CORE',SYSDATE,SYSDATE,1),
  (38,'Core Rebates validation check','REMICADE','REBATES','CORE',SYSDATE,SYSDATE,1),
  (39,'Core Rebates validation check','RISPERDAL CONSTA','REBATES','CORE',SYSDATE,SYSDATE,1),
  (40,'Core Rebates validation check','SIMPONI','REBATES','CORE',SYSDATE,SYSDATE,1),
  (41,'Core Rebates validation check','SIMPONI ARIA','REBATES','CORE',SYSDATE,SYSDATE,1),
  (42,'Core Rebates validation check','SPRAVATO','REBATES','CORE',SYSDATE,SYSDATE,1),
  (43,'Core Rebates validation check','STELARA','REBATES','CORE',SYSDATE,SYSDATE,1),
  (44,'Core Rebates validation check','SYMTUZA','REBATES','CORE',SYSDATE,SYSDATE,1),
  (45,'Core Rebates validation check','TREMFYA','REBATES','CORE',SYSDATE,SYSDATE,1),
  (46,'Core Rebates validation check','XARELTO','REBATES','CORE',SYSDATE,SYSDATE,1),
  (47,'Core Rebates validation check','YONDELIS','REBATES','CORE',SYSDATE,SYSDATE,1),
  (48,'Utilization Tot Gross sales validation check','UTLZ','GRS_SLS','CORE',SYSDATE,SYSDATE,1),
  (49,'Utilization Gross sales validation check','DARZALEX','GRS_SLS','CORE',SYSDATE,SYSDATE,1),
  (50,'Utilization Gross sales validation check','DOXIL','GRS_SLS','CORE',SYSDATE,SYSDATE,1),
  (51,'Utilization Gross sales validation check','ERLEADA','GRS_SLS','CORE',SYSDATE,SYSDATE,1),
  (52,'Utilization Gross sales validation check','INVEGA','GRS_SLS','CORE',SYSDATE,SYSDATE,1),
  (53,'Utilization Gross sales validation check','INVEGA SUSTENNA','GRS_SLS','CORE',SYSDATE,SYSDATE,1),
  (54,'Utilization Gross sales validation check','INVEGA TRINZA','GRS_SLS','CORE',SYSDATE,SYSDATE,1),
  (55,'Utilization Gross sales validation check','INVOKAMET','GRS_SLS','CORE',SYSDATE,SYSDATE,1),
  (56,'Utilization Gross sales validation check','INVOKAMET XR','GRS_SLS','CORE',SYSDATE,SYSDATE,1),
  (57,'Utilization Gross sales validation check','INVOKANA','GRS_SLS','CORE',SYSDATE,SYSDATE,1),
  (58,'Utilization Gross sales validation check','PREZCOBIX','GRS_SLS','CORE',SYSDATE,SYSDATE,1),
  (59,'Utilization Gross sales validation check','PREZISTA','GRS_SLS','CORE',SYSDATE,SYSDATE,1),
  (60,'Utilization Gross sales validation check','PROCRIT','GRS_SLS','CORE',SYSDATE,SYSDATE,1),
  (61,'Utilization Gross sales validation check','REMICADE','GRS_SLS','CORE',SYSDATE,SYSDATE,1),
  (62,'Utilization Gross sales validation check','RISPERDAL CONSTA','GRS_SLS','CORE',SYSDATE,SYSDATE,1),
  (63,'Utilization Gross sales validation check','SIMPONI','GRS_SLS','CORE',SYSDATE,SYSDATE,1),
  (64,'Utilization Gross sales validation check','SIMPONI ARIA','GRS_SLS','CORE',SYSDATE,SYSDATE,1),
  (65,'Utilization Gross sales validation check','SPRAVATO','GRS_SLS','CORE',SYSDATE,SYSDATE,1),
  (66,'Utilization Gross sales validation check','STELARA','GRS_SLS','CORE',SYSDATE,SYSDATE,1),
  (67,'Utilization Gross sales validation check','SYMTUZA','GRS_SLS','CORE',SYSDATE,SYSDATE,1),
  (68,'Utilization Gross sales validation check','TREMFYA','GRS_SLS','CORE',SYSDATE,SYSDATE,1),
  (69,'Utilization Gross sales validation check','XARELTO','GRS_SLS','CORE',SYSDATE,SYSDATE,1),
  (70,'Utilization Gross sales validation check','YONDELIS','GRS_SLS','CORE',SYSDATE,SYSDATE,1),
  (71,'Utilization Gross sales validation check','ZYTIGA','GRS_SLS','CORE',SYSDATE,SYSDATE,1),
  (72,'Utilization Gross sales validation check','UTLZ','GRS_SLS','CORE',SYSDATE,SYSDATE,1),
  (73,'Utilization Tot metric quantity check','UTLZ','UNIT','CORE',SYSDATE,SYSDATE,1),
  (74,'Utilization metric quantity check','DARZALEX','UNIT','CORE',SYSDATE,SYSDATE,1),
  (75,'Utilization metric quantity check','DOXIL','UNIT','CORE',SYSDATE,SYSDATE,1),
  (76,'Utilization metric quantity check','ERLEADA','UNIT','CORE',SYSDATE,SYSDATE,1),
  (77,'Utilization metric quantity check','INVEGA','UNIT','CORE',SYSDATE,SYSDATE,1),
  (78,'Utilization metric quantity check','INVEGA SUSTENNA','UNIT','CORE',SYSDATE,SYSDATE,1),
  (79,'Utilization metric quantity check','INVEGA TRINZA','UNIT','CORE',SYSDATE,SYSDATE,1),
  (80,'Utilization metric quantity check','INVOKAMET','UNIT','CORE',SYSDATE,SYSDATE,1),
  (81,'Utilization metric quantity check','INVOKAMET XR','UNIT','CORE',SYSDATE,SYSDATE,1),
  (82,'Utilization metric quantity check','INVOKANA','UNIT','CORE',SYSDATE,SYSDATE,1),
  (83,'Utilization metric quantity check','PREZCOBIX','UNIT','CORE',SYSDATE,SYSDATE,1),
  (84,'Utilization metric quantity check','PREZISTA','UNIT','CORE',SYSDATE,SYSDATE,1),
  (85,'Utilization metric quantity check','PROCRIT','UNIT','CORE',SYSDATE,SYSDATE,1),
  (86,'Utilization metric quantity check','REMICADE','UNIT','CORE',SYSDATE,SYSDATE,1),
  (87,'Utilization metric quantity check','RISPERDAL CONSTA','UNIT','CORE',SYSDATE,SYSDATE,1),
  (88,'Utilization metric quantity check','SIMPONI','UNIT','CORE',SYSDATE,SYSDATE,1),
  (89,'Utilization metric quantity check','SIMPONI ARIA','UNIT','CORE',SYSDATE,SYSDATE,1),
  (90,'Utilization metric quantity check','SPRAVATO','UNIT','CORE',SYSDATE,SYSDATE,1),
  (91,'Utilization metric quantity check','STELARA','UNIT','CORE',SYSDATE,SYSDATE,1),
  (92,'Utilization metric quantity check','SYMTUZA','UNIT','CORE',SYSDATE,SYSDATE,1),
  (93,'Utilization metric quantity check','TREMFYA','UNIT','CORE',SYSDATE,SYSDATE,1),
  (94,'Utilization metric quantity check','XARELTO','UNIT','CORE',SYSDATE,SYSDATE,1),
  (95,'Utilization metric quantity check','YONDELIS','UNIT','CORE',SYSDATE,SYSDATE,1),
  (96,'Utilization metric quantity check','ZYTIGA','UNIT','CORE',SYSDATE,SYSDATE,1),
  (97,'Utilization tot prescrpions check','UTLZ','PRESCRIPTION','CORE',SYSDATE,SYSDATE,1),
  (98,'Utilization prescrpions check','DARZALEX','PRESCRIPTION','CORE',SYSDATE,SYSDATE,1),
  (99,'Utilization prescrpions check','DOXIL','PRESCRIPTION','CORE',SYSDATE,SYSDATE,1),
  (100,'Utilization prescrpions check','ERLEADA','PRESCRIPTION','CORE',SYSDATE,SYSDATE,1),
  (101,'Utilization prescrpions check','INVEGA','PRESCRIPTION','CORE',SYSDATE,SYSDATE,1),
  (102,'Utilization prescrpions check','INVEGA SUSTENNA','PRESCRIPTION','CORE',SYSDATE,SYSDATE,1),
  (103,'Utilization prescrpions check','INVEGA TRINZA','PRESCRIPTION','CORE',SYSDATE,SYSDATE,1),
  (104,'Utilization prescrpions check','INVOKAMET','PRESCRIPTION','CORE',SYSDATE,SYSDATE,1),
  (105,'Utilization prescrpions check','INVOKAMET XR','PRESCRIPTION','CORE',SYSDATE,SYSDATE,1),
  (106,'Utilization prescrpions check','INVOKANA','PRESCRIPTION','CORE',SYSDATE,SYSDATE,1),
  (107,'Utilization prescrpions check','PREZCOBIX','PRESCRIPTION','CORE',SYSDATE,SYSDATE,1),
  (108,'Utilization prescrpions check','PREZISTA','PRESCRIPTION','CORE',SYSDATE,SYSDATE,1),
  (109,'Utilization prescrpions check','PROCRIT','PRESCRIPTION','CORE',SYSDATE,SYSDATE,1),
  (110,'Utilization prescrpions check','REMICADE','PRESCRIPTION','CORE',SYSDATE,SYSDATE,1),
  (111,'Utilization prescrpions check','RISPERDAL CONSTA','PRESCRIPTION','CORE',SYSDATE,SYSDATE,1),
  (112,'Utilization prescrpions check','SIMPONI','PRESCRIPTION','CORE',SYSDATE,SYSDATE,1),
  (113,'Utilization prescrpions check','SIMPONI ARIA','PRESCRIPTION','CORE',SYSDATE,SYSDATE,1),
  (114,'Utilization prescrpions check','SPRAVATO','PRESCRIPTION','CORE',SYSDATE,SYSDATE,1),
  (115,'Utilization prescrpions check','STELARA','PRESCRIPTION','CORE',SYSDATE,SYSDATE,1),
  (116,'Utilization prescrpions check','SYMTUZA','PRESCRIPTION','CORE',SYSDATE,SYSDATE,1),
  (117,'Utilization prescrpions check','TREMFYA','PRESCRIPTION','CORE',SYSDATE,SYSDATE,1),
  (118,'Utilization prescrpions check','XARELTO','PRESCRIPTION','CORE',SYSDATE,SYSDATE,1),
  (119,'Utilization prescrpions check','YONDELIS','PRESCRIPTION','CORE',SYSDATE,SYSDATE,1),
  (120,'Utilization prescrpions check','ZYTIGA','PRESCRIPTION','CORE',SYSDATE,SYSDATE,1),
  (121,'Utilization prescrpions check','ZYTIGA','PRESCRIPTION','CORE',SYSDATE,SYSDATE,1),
  (122,'Core Tot Sales check from chargeback','CGBK','SALES','CORE',SYSDATE,SYSDATE,1),
  (123,'Core Sales check from chargeback','DARZALEX','SALES','CORE',SYSDATE,SYSDATE,1),
  (124,'Core Sales check from chargeback','DOXIL','SALES','CORE',SYSDATE,SYSDATE,1),
  (125,'Core Sales check from chargeback','ERLEADA','SALES','CORE',SYSDATE,SYSDATE,1),
  (126,'Core Sales check from chargeback','INVEGA','SALES','CORE',SYSDATE,SYSDATE,1),
  (127,'Core Sales check from chargeback','INVEGA SUSTENNA','SALES','CORE',SYSDATE,SYSDATE,1),
  (128,'Core Sales check from chargeback','INVEGA TRINZA','SALES','CORE',SYSDATE,SYSDATE,1),
  (129,'Core Sales check from chargeback','INVOKAMET','SALES','CORE',SYSDATE,SYSDATE,1),
  (130,'Core Sales check from chargeback','INVOKAMET XR','SALES','CORE',SYSDATE,SYSDATE,1),
  (131,'Core Sales check from chargeback','INVOKANA','SALES','CORE',SYSDATE,SYSDATE,1),
  (132,'Core Sales check from chargeback','PREZCOBIX','SALES','CORE',SYSDATE,SYSDATE,1),
  (133,'Core Sales check from chargeback','PREZISTA','SALES','CORE',SYSDATE,SYSDATE,1),
  (134,'Core Sales check from chargeback','PROCRIT','SALES','CORE',SYSDATE,SYSDATE,1),
  (135,'Core Sales check from chargeback','REMICADE','SALES','CORE',SYSDATE,SYSDATE,1),
  (136,'Core Sales check from chargeback','RISPERDAL CONSTA','SALES','CORE',SYSDATE,SYSDATE,1),
  (137,'Core Sales check from chargeback','SIMPONI','SALES','CORE',SYSDATE,SYSDATE,1),
  (138,'Core Sales check from chargeback','SIMPONI ARIA','SALES','CORE',SYSDATE,SYSDATE,1),
  (139,'Core Sales check from chargeback','SPRAVATO','SALES','CORE',SYSDATE,SYSDATE,1),
  (140,'Core Sales check from chargeback','STELARA','SALES','CORE',SYSDATE,SYSDATE,1),
  (141,'Core Sales check from chargeback','SYMTUZA','SALES','CORE',SYSDATE,SYSDATE,1),
  (142,'Core Sales check from chargeback','TREMFYA','SALES','CORE',SYSDATE,SYSDATE,1),
  (143,'Core Sales check from chargeback','XARELTO','SALES','CORE',SYSDATE,SYSDATE,1),
  (144,'Core Sales check from chargeback','YONDELIS','SALES','CORE',SYSDATE,SYSDATE,1),
  (145,'Core Sales check from chargeback','ZYTIGA','SALES','CORE',SYSDATE,SYSDATE,1),
  (146,'Core Tot dollar amount validation check for Adjudication','ADJITEM','UNIT','CORE',SYSDATE,SYSDATE,1),
  (147,'Core dollar amount validation check for Adjudication','DARZALEX','UNIT','CORE',SYSDATE,SYSDATE,1),
  (148,'Core dollar amount validation check for Adjudication','DOXIL','UNIT','CORE',SYSDATE,SYSDATE,1),
  (149,'Core dollar amount validation check for Adjudication','ERLEADA','UNIT','CORE',SYSDATE,SYSDATE,1),
  (150,'Core dollar amount validation check for Adjudication','INVEGA','UNIT','CORE',SYSDATE,SYSDATE,1),
  (151,'Core dollar amount validation check for Adjudication','INVEGA SUSTENNA','UNIT','CORE',SYSDATE,SYSDATE,1),
  (152,'Core dollar amount validation check for Adjudication','INVEGA TRINZA','UNIT','CORE',SYSDATE,SYSDATE,1),
  (153,'Core dollar amount validation check for Adjudication','INVOKAMET','UNIT','CORE',SYSDATE,SYSDATE,1),
  (154,'Core dollar amount validation check for Adjudication','INVOKAMET XR','UNIT','CORE',SYSDATE,SYSDATE,1),
  (155,'Core dollar amount validation check for Adjudication','INVOKANA','UNIT','CORE',SYSDATE,SYSDATE,1),
  (156,'Core dollar amount validation check for Adjudication','PREZCOBIX','UNIT','CORE',SYSDATE,SYSDATE,1),
  (157,'Core dollar amount validation check for Adjudication','PREZISTA','UNIT','CORE',SYSDATE,SYSDATE,1),
  (158,'Core dollar amount validation check for Adjudication','PROCRIT','UNIT','CORE',SYSDATE,SYSDATE,1),
  (159,'Core dollar amount validation check for Adjudication','REMICADE','UNIT','CORE',SYSDATE,SYSDATE,1),
  (160,'Core dollar amount validation check for Adjudication','RISPERDAL CONSTA','UNIT','CORE',SYSDATE,SYSDATE,1),
  (161,'Core dollar amount validation check for Adjudication','SIMPONI','UNIT','CORE',SYSDATE,SYSDATE,1),
  (162,'Core dollar amount validation check for Adjudication','SIMPONI ARIA','UNIT','CORE',SYSDATE,SYSDATE,1),
  (163,'Core dollar amount validation check for Adjudication','SPRAVATO','UNIT','CORE',SYSDATE,SYSDATE,1),
  (164,'Core dollar amount validation check for Adjudication','STELARA','UNIT','CORE',SYSDATE,SYSDATE,1),
  (165,'Core dollar amount validation check for Adjudication','SYMTUZA','UNIT','CORE',SYSDATE,SYSDATE,1),
  (166,'Core dollar amount validation check for Adjudication','TREMFYA','UNIT','CORE',SYSDATE,SYSDATE,1),
  (167,'Core dollar amount validation check for Adjudication','XARELTO','UNIT','CORE',SYSDATE,SYSDATE,1),
  (168,'Core dollar amount validation check for Adjudication','YONDELIS','UNIT','CORE',SYSDATE,SYSDATE,1),
  (169,'Core dollar amount validation check for Adjudication','ZYTIGA','UNIT','CORE',SYSDATE,SYSDATE,1),
  (170,'Core Tot unit validation check for submission','SUBMITM','UNIT','CORE',SYSDATE,SYSDATE,1),
  (171,'Core unit validation check for submission','DARZALEX','UNIT','CORE',SYSDATE,SYSDATE,1),
  (172,'Core unit validation check for submission','DOXIL','UNIT','CORE',SYSDATE,SYSDATE,1),
  (173,'Core unit validation check for submission','ERLEADA','UNIT','CORE',SYSDATE,SYSDATE,1),
  (174,'Core unit validation check for submission','INVEGA','UNIT','CORE',SYSDATE,SYSDATE,1),
  (175,'Core unit validation check for submission','INVEGA SUSTENNA','UNIT','CORE',SYSDATE,SYSDATE,1),
  (176,'Core unit validation check for submission','INVEGA TRINZA','UNIT','CORE',SYSDATE,SYSDATE,1),
  (177,'Core unit validation check for submission','INVOKAMET','UNIT','CORE',SYSDATE,SYSDATE,1),
  (178,'Core unit validation check for submission','INVOKAMET XR','UNIT','CORE',SYSDATE,SYSDATE,1),
  (179,'Core unit validation check for submission','INVOKANA','UNIT','CORE',SYSDATE,SYSDATE,1),
  (180,'Core unit validation check for submission','PREZCOBIX','UNIT','CORE',SYSDATE,SYSDATE,1),
  (181,'Core unit validation check for submission','PREZISTA','UNIT','CORE',SYSDATE,SYSDATE,1),
  (182,'Core unit validation check for submission','PROCRIT','UNIT','CORE',SYSDATE,SYSDATE,1),
  (183,'Core unit validation check for submission','REMICADE','UNIT','CORE',SYSDATE,SYSDATE,1),
  (184,'Core unit validation check for submission','RISPERDAL CONSTA','UNIT','CORE',SYSDATE,SYSDATE,1),
  (185,'Core unit validation check for submission','SIMPONI','UNIT','CORE',SYSDATE,SYSDATE,1),
  (186,'Core unit validation check for submission','SIMPONI ARIA','UNIT','CORE',SYSDATE,SYSDATE,1),
  (187,'Core unit validation check for submission','SPRAVATO','UNIT','CORE',SYSDATE,SYSDATE,1),
  (188,'Core unit validation check for submission','STELARA','UNIT','CORE',SYSDATE,SYSDATE,1),
  (189,'Core unit validation check for submission','SYMTUZA','UNIT','CORE',SYSDATE,SYSDATE,1),
  (190,'Core unit validation check for submission','TREMFYA','UNIT','CORE',SYSDATE,SYSDATE,1),
  (191,'Core unit validation check for submission','XARELTO','UNIT','CORE',SYSDATE,SYSDATE,1),
  (192,'Core unit validation check for submission','YONDELIS','UNIT','CORE',SYSDATE,SYSDATE,1),
  (193,'Core unit validation check for submission','ZYTIGA','UNIT','CORE',SYSDATE,SYSDATE,1),
  (194,'Core Tot unit validation check for chargeback','CGBK','UNIT','CORE',SYSDATE,SYSDATE,1),
  (195,'Core unit validation check for chargeback','DARZALEX','UNIT','CORE',SYSDATE,SYSDATE,1),
  (196,'Core unit validation check for chargeback','DOXIL','UNIT','CORE',SYSDATE,SYSDATE,1),
  (197,'Core unit validation check for chargeback','ERLEADA','UNIT','CORE',SYSDATE,SYSDATE,1),
  (198,'Core unit validation check for chargeback','INVEGA','UNIT','CORE',SYSDATE,SYSDATE,1),
  (199,'Core unit validation check for chargeback','INVEGA SUSTENNA','UNIT','CORE',SYSDATE,SYSDATE,1),
  (200,'Core unit validation check for chargeback','INVEGA TRINZA','UNIT','CORE',SYSDATE,SYSDATE,1),
  (201,'Core unit validation check for chargeback','INVOKAMET','UNIT','CORE',SYSDATE,SYSDATE,1),
  (202,'Core unit validation check for chargeback','INVOKAMET XR','UNIT','CORE',SYSDATE,SYSDATE,1),
  (203,'Core unit validation check for chargeback','INVOKANA','UNIT','CORE',SYSDATE,SYSDATE,1),
  (204,'Core unit validation check for chargeback','PREZCOBIX','UNIT','CORE',SYSDATE,SYSDATE,1),
  (205,'Core unit validation check for chargeback','PREZISTA','UNIT','CORE',SYSDATE,SYSDATE,1),
  (206,'Core unit validation check for chargeback','PROCRIT','UNIT','CORE',SYSDATE,SYSDATE,1),
  (207,'Core unit validation check for chargeback','REMICADE','UNIT','CORE',SYSDATE,SYSDATE,1),
  (208,'Core unit validation check for chargeback','RISPERDAL CONSTA','UNIT','CORE',SYSDATE,SYSDATE,1),
  (209,'Core unit validation check for chargeback','SIMPONI','UNIT','CORE',SYSDATE,SYSDATE,1),
  (210,'Core unit validation check for chargeback','SIMPONI ARIA','UNIT','CORE',SYSDATE,SYSDATE,1),
  (211,'Core unit validation check for chargeback','SPRAVATO','UNIT','CORE',SYSDATE,SYSDATE,1),
  (212,'Core unit validation check for chargeback','STELARA','UNIT','CORE',SYSDATE,SYSDATE,1),
  (213,'Core unit validation check for chargeback','SYMTUZA','UNIT','CORE',SYSDATE,SYSDATE,1),
  (214,'Core unit validation check for chargeback','TREMFYA','UNIT','CORE',SYSDATE,SYSDATE,1),
  (215,'Core unit validation check for chargeback','XARELTO','UNIT','CORE',SYSDATE,SYSDATE,1),
  (216,'Core unit validation check for chargeback','YONDELIS','UNIT','CORE',SYSDATE,SYSDATE,1),
  (217,'Core unit validation check for chargeback','ZYTIGA','UNIT','CORE',SYSDATE,SYSDATE,1),
  (218,'Tot Count of Trading Partner check','TRAD_PTNR','TRAD_PTNR','CORE',SYSDATE,SYSDATE,1),
  (219,'Tot Count of Active Trading Partner check','TRAD_PTNR','TRAD_PTNR','CORE',SYSDATE,SYSDATE,1),
  (220,'Tot Count of Inactive Trading Partner check','TRAD_PTNR','TRAD_PTNR','CORE',SYSDATE,SYSDATE,1),
  (221,'Tot Count of Newly Added Trading Partner check','TRAD_PTNR','TRAD_PTNR','CORE',SYSDATE,SYSDATE,1),
  (222,'Newly Added Trading Partner check','TRAD_PTNR','TRAD_PTNR','CORE',SYSDATE,SYSDATE,1),
  (223,'Tot Count of Deleted Trading Partner check','TRAD_PTNR','TRAD_PTNR','CORE',SYSDATE,SYSDATE,1),
  (224,'Deleted Trading Partner check','TRAD_PTNR','TRAD_PTNR','CORE',SYSDATE,SYSDATE,1),
  (225,'Tot Count of Updated Trading Partner Name check','TRAD_PTNR','TRAD_PTNR','CORE',SYSDATE,SYSDATE,1),
  (226,'Updated Trading Partner Name check','TRAD_PTNR','TRAD_PTNR','CORE',SYSDATE,SYSDATE,1),
  (227,'Tot Count of Updated Trading Partner COT check','TRAD_PTNR','TRAD_PTNR','CORE',SYSDATE,SYSDATE,1),
  (228,'Updated Trading Partner COT check','TRAD_PTNR','TRAD_PTNR','CORE',SYSDATE,SYSDATE,1),
  (229,'Tot Count of Contract check','CNTRC','CNTRC','CORE',SYSDATE,SYSDATE,1),
  (230,'Tot Count of Active Contract check','CNTRC','CNTRC','CORE',SYSDATE,SYSDATE,1),
  (231,'Tot Count of Inactive Contract check','CNTRC','CNTRC','CORE',SYSDATE,SYSDATE,1),
  (232,'Tot Count of Newly Added Contract check','CNTRC','CNTRC','CORE',SYSDATE,SYSDATE,1),
  (233,'Newly Added Contract check','CNTRC','CNTRC','CORE',SYSDATE,SYSDATE,1),
  (234,'Tot Count of Deleted Contract check','CNTRC','CNTRC','CORE',SYSDATE,SYSDATE,1),
  (235,'Deleted Contract check','CNTRC','CNTRC','CORE',SYSDATE,SYSDATE,1),
  (236,'Tot Count of Updated Contract Title check','CNTRC','CNTRC','CORE',SYSDATE,SYSDATE,1),
  (237,'Updated Contract Title check','CNTRC','CNTRC','CORE',SYSDATE,SYSDATE,1),
  (238,'Tot Count of Updated Contract-Trading Partner check','CNTRC','CNTRC','CORE',SYSDATE,SYSDATE,1),
  (239,'Updated Contract-Trading Partner check','CNTRC','CNTRC','CORE',SYSDATE,SYSDATE,1),
  (240,'Tot Count of Product check','PROD','PROD','CORE',SYSDATE,SYSDATE,1),
  (241,'Tot Count of Active Product check','PROD','PROD','CORE',SYSDATE,SYSDATE,1),
  (242,'Tot Count of Inactive Product check','PROD','PROD','CORE',SYSDATE,SYSDATE,1),
  (243,'Tot Count of Newly Added Product check','PROD','PROD','CORE',SYSDATE,SYSDATE,1),
  (244,'Newly Added Product check','PROD','PROD','CORE',SYSDATE,SYSDATE,1),
  (245,'Tot Count of Deleted Product check','PROD','PROD','CORE',SYSDATE,SYSDATE,1),
  (246,'Deleted Product check','PROD','PROD','CORE',SYSDATE,SYSDATE,1),
  (247,'Tot Count of Updated Product Desc check','PROD','PROD','CORE',SYSDATE,SYSDATE,1),
  (248,'Updated Product Desc check','PROD','PROD','CORE',SYSDATE,SYSDATE,1),
  (249,'Table record count','dm_f_sls_adj','TABLE','CORE',SYSDATE,SYSDATE,1),
  (250,'Table record count','dm_f_sls_cgbk','TABLE','CORE',SYSDATE,SYSDATE,1),
  (251,'Table record count','dm_f_utlz','TABLE','CORE',SYSDATE,SYSDATE,1),
  (252,'Table record count','dm_f_sls_sbmn','TABLE','CORE',SYSDATE,SYSDATE,1),
  (253,'Table record count','dm_f_idnshiptosales_mdm_file_n','TABLE','CORE',SYSDATE,SYSDATE,1),
  (254,'Table record count','dm_f_carsis_allsales_sf','TABLE','CORE',SYSDATE,SYSDATE,1),
  (255,'Table record count','dm_f_vw_onemd_scg_mthlysls_fscl','TABLE','CORE',SYSDATE,SYSDATE,1),
  (256,'Table record count','dm_f_esi_sls_mly','TABLE','CORE',SYSDATE,SYSDATE,1),
  (257,'Table record count','dm_f_esi_act_sls_mly','TABLE','CORE',SYSDATE,SYSDATE,1),
  (258,'Table record count','dm_d_prod_to_prod_rel','TABLE','CORE',SYSDATE,SYSDATE,1),
  (259,'Table record count','dm_d_prod_basis_hist','TABLE','CORE',SYSDATE,SYSDATE,1),
  (260,'Table record count','dm_d_prod_char','TABLE','CORE',SYSDATE,SYSDATE,1),
  (261,'Table record count','dm_d_prod_xref','TABLE','CORE',SYSDATE,SYSDATE,1),
  (262,'Table record count','dm_d_rpt_prod_xref','TABLE','CORE',SYSDATE,SYSDATE,1),
  (263,'Table record count','dm_d_cntrc_amnd_hist','TABLE','CORE',SYSDATE,SYSDATE,1),
  (264,'Table record count','dm_d_cntrc_prc_grp','TABLE','CORE',SYSDATE,SYSDATE,1),
  (265,'Table record count','dm_d_cntrc','TABLE','CORE',SYSDATE,SYSDATE,1),
  (266,'Table record count','dm_d_cntrc_expn_vld','TABLE','CORE',SYSDATE,SYSDATE,1),
  (267,'Table record count','dm_d_cntrc_prc_grp_prod_line','TABLE','CORE',SYSDATE,SYSDATE,1),
  (268,'Table record count','dm_d_trad_ptnr','TABLE','CORE',SYSDATE,SYSDATE,1),
  (269,'Table record count','dm_d_trad_ptnr_cntct','TABLE','CORE',SYSDATE,SYSDATE,1),
  (270,'Table record count','dm_d_trad_ptnr_addr','TABLE','CORE',SYSDATE,SYSDATE,1),
  (271,'Table record count','dm_d_trad_ptnr_mbr_hist','TABLE','CORE',SYSDATE,SYSDATE,1),
  (272,'Table record count','dm_d_trad_ptnr_buid_sts_hist','TABLE','CORE',SYSDATE,SYSDATE,1),
  (273,'Table record count','dm_d_cpp_mq_elig_cust','TABLE','CORE',SYSDATE,SYSDATE,1),
  (274,'Table record count','dm_d_cpp_mq_elig_cust_tmpl','TABLE','CORE',SYSDATE,SYSDATE,1),
  (275,'Table record count','dm_d_cpp_eq_elig_cust','TABLE','CORE',SYSDATE,SYSDATE,1),
  (276,'Table record count','dm_d_cpp_eq_elig_cust_tmpl','TABLE','CORE',SYSDATE,SYSDATE,1),
  (277,'Table record count','dm_f_cpp_eq_cgbk','TABLE','CORE',SYSDATE,SYSDATE,1),
  (278,'Table record count','dm_f_cpp_eq_grs_sls_utlz','TABLE','CORE',SYSDATE,SYSDATE,1),
  (279,'Table record count','dm_f_cpp_eq_rebt','TABLE','CORE',SYSDATE,SYSDATE,1),
  (280,'Table record count','dm_f_cpp_mq_cgbk','TABLE','CORE',SYSDATE,SYSDATE,1),
  (281,'Table record count','dm_f_cpp_mq_grs_sls_utlz','TABLE','CORE',SYSDATE,SYSDATE,1),
  (282,'Table record count','dm_f_cpp_mq_rebt','TABLE','CORE',SYSDATE,SYSDATE,1),
  (283,'Table record count','jmap_atm_account','TABLE','CORE',SYSDATE,SYSDATE,1),
  (284,'Core Tot TA Sales check from submission','SUBMITM','SALES','CORE',SYSDATE,SYSDATE,1),
  (285,'Core TA Sales check from submission','CVM','SALES','CORE',SYSDATE,SYSDATE,1),
  (286,'Core TA Sales check from submission','EP','SALES','CORE',SYSDATE,SYSDATE,1),
  (287,'Core TA Sales check from submission','ID','SALES','CORE',SYSDATE,SYSDATE,1),
  (288,'Core TA Sales check from submission','IMM','SALES','CORE',SYSDATE,SYSDATE,1),
  (289,'Core TA Sales check from submission','NS','SALES','CORE',SYSDATE,SYSDATE,1),
  (290,'Core TA Sales check from submission','ONC','SALES','CORE',SYSDATE,SYSDATE,1),
  (291,'Core Tot TA unit validation check for submission','SUBMITM','UNIT','CORE',SYSDATE,SYSDATE,1),
  (293,'Core TA unit validation check for submission','CVM','UNIT','CORE',SYSDATE,SYSDATE,3),
  (294,'Core TA unit validation check for submission','EP','UNIT','CORE',SYSDATE,SYSDATE,4),
  (295,'Core TA unit validation check for submission','ID','UNIT','CORE',SYSDATE,SYSDATE,5),
  (296,'Core TA unit validation check for submission','IMM','UNIT','CORE',SYSDATE,SYSDATE,6),
  (297,'Core TA unit validation check for submission','NS','UNIT','CORE',SYSDATE,SYSDATE,7),
  (298,'Core TA unit validation check for submission','ONC','UNIT','CORE',SYSDATE,SYSDATE,8),
  (299,'Core Tot TA Rebates validation check','ADJITEM','REBATES','CORE',SYSDATE,SYSDATE,1),
  (300,'Core TA Rebates validation check','CVM','REBATES','CORE',SYSDATE,SYSDATE,1),
  (301,'Core TA Rebates validation check','EP','REBATES','CORE',SYSDATE,SYSDATE,1),
  (302,'Core TA Rebates validation check','ID','REBATES','CORE',SYSDATE,SYSDATE,1),
  (303,'Core TA Rebates validation check','IMM','REBATES','CORE',SYSDATE,SYSDATE,1),
  (304,'Core TA Rebates validation check','NS','REBATES','CORE',SYSDATE,SYSDATE,1),
  (305,'Core TA Rebates validation check','ONC','REBATES','CORE',SYSDATE,SYSDATE,1),
  (306,'Core Tot TA dollar amount validation check for Adjudication','ADJITEM','AMOUNT','CORE',SYSDATE,SYSDATE,1),
  (307,'Core TA dollar amount validation check for Adjudication','CVM','AMOUNT','CORE',SYSDATE,SYSDATE,1),
  (308,'Core TA dollar amount validation check for Adjudication','EP','AMOUNT','CORE',SYSDATE,SYSDATE,1),
  (309,'Core TA dollar amount validation check for Adjudication','ID','AMOUNT','CORE',SYSDATE,SYSDATE,1),
  (310,'Core TA dollar amount validation check for Adjudication','IMM','AMOUNT','CORE',SYSDATE,SYSDATE,1),
  (311,'Core TA dollar amount validation check for Adjudication','NS','AMOUNT','CORE',SYSDATE,SYSDATE,1),
  (312,'Core TA dollar amount validation check for Adjudication','ONC','AMOUNT','CORE',SYSDATE,SYSDATE,1),
  (313,'Core Tot TA Sales check from chargeback','CGBK','SALES','CORE',SYSDATE,SYSDATE,1),
  (314,'Core TA Sales check from chargeback','CVM','SALES','CORE',SYSDATE,SYSDATE,1),
  (315,'Core TA Sales check from chargeback','EP','SALES','CORE',SYSDATE,SYSDATE,2),
  (316,'Core TA Sales check from chargeback','ID','SALES','CORE',SYSDATE,SYSDATE,3),
  (317,'Core TA Sales check from chargeback','IMM','SALES','CORE',SYSDATE,SYSDATE,4),
  (318,'Core TA Sales check from chargeback','NS','SALES','CORE',SYSDATE,SYSDATE,5),
  (319,'Core TA Sales check from chargeback','ONC','SALES','CORE',SYSDATE,SYSDATE,6),
  (320,'Core Tot TA unit validation check for chargeback','CGBK','UNIT','CORE',SYSDATE,SYSDATE,1),
  (321,'Core TA unit validation check for chargeback','CVM','UNIT','CORE',SYSDATE,SYSDATE,1),
  (322,'Core TA unit validation check for chargeback','EP','UNIT','CORE',SYSDATE,SYSDATE,1),
  (323,'Core TA unit validation check for chargeback','ID','UNIT','CORE',SYSDATE,SYSDATE,1),
  (324,'Core TA unit validation check for chargeback','IMM','UNIT','CORE',SYSDATE,SYSDATE,1),
  (325,'Core TA unit validation check for chargeback','NS','UNIT','CORE',SYSDATE,SYSDATE,1),
  (326,'Core TA unit validation check for chargeback','ONC','UNIT','CORE',SYSDATE,SYSDATE,1),
  (327,'Utilization Tot TA Gross sales validation check','UTLZ','GRS_SLS','CORE',SYSDATE,SYSDATE,1),
  (328,'Utilization TA Gross sales validation check','CVM','GRS_SLS','CORE',SYSDATE,SYSDATE,1),
  (329,'Utilization TA Gross sales validation check','EP','GRS_SLS','CORE',SYSDATE,SYSDATE,1),
  (330,'Utilization TA Gross sales validation check','ID','GRS_SLS','CORE',SYSDATE,SYSDATE,1),
  (331,'Utilization TA Gross sales validation check','IMM','GRS_SLS','CORE',SYSDATE,SYSDATE,1),
  (332,'Utilization TA Gross sales validation check','NS','GRS_SLS','CORE',SYSDATE,SYSDATE,1),
  (333,'Utilization TA Gross sales validation check','ONC','GRS_SLS','CORE',SYSDATE,SYSDATE,1),
  (334,'Utilization Tot TA metric quantity check','UTLZ','UNIT','CORE',SYSDATE,SYSDATE,1),
  (335,'Utilization TA metric quantity check','CVM','UNIT','CORE',SYSDATE,SYSDATE,1),
  (336,'Utilization TA metric quantity check','EP','UNIT','CORE',SYSDATE,SYSDATE,1),
  (337,'Utilization TA metric quantity check','ID','UNIT','CORE',SYSDATE,SYSDATE,1),
  (338,'Utilization TA metric quantity check','IMM','UNIT','CORE',SYSDATE,SYSDATE,1),
  (339,'Utilization TA metric quantity check','NS','UNIT','CORE',SYSDATE,SYSDATE,1),
  (340,'Utilization TA metric quantity check','ONC','UNIT','CORE',SYSDATE,SYSDATE,1),
  (341,'Utilization Tot TA prescrpions check','UTLZ','PRESCRIPTION','CORE',SYSDATE,SYSDATE,1),
  (342,'Utilization TA prescrpions check','CVM','PRESCRIPTION','CORE',SYSDATE,SYSDATE,1),
  (343,'Utilization TA prescrpions check','EP','PRESCRIPTION','CORE',SYSDATE,SYSDATE,1),
  (344,'Utilization TA prescrpions check','ID','PRESCRIPTION','CORE',SYSDATE,SYSDATE,1),
  (345,'Utilization TA prescrpions check','IMM','PRESCRIPTION','CORE',SYSDATE,SYSDATE,1),
  (346,'Utilization TA prescrpions check','NS','PRESCRIPTION','CORE',SYSDATE,SYSDATE,1),
  (347,'Utilization TA prescrpions check','ONC','PRESCRIPTION','CORE',SYSDATE,SYSDATE,1);
